### ISSUE TITLE
Skip new getting started wizard

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/dev-server#114]
![grafik](https://user-images.githubusercontent.com/17641229/133436771-60514a6e-f81d-49c8-a3f8-41cbb366b2bb.png)

**Comment by UncleSamSwiss** [comment]
It looks like this is a problem with your setup.

If `dev-server setup` ran through properly, it would have disabled the wizard:
https://github.com/ioBroker/dev-server/blob/b9998c8fc1474494217cfbbcaa53d0676ea5bb3c/src/index.ts#L1132

**Comment by AlCalzone** [comment]
👍🏻 Couldn't reproduce it after the first time

**Comment by AlCalzone** [comment]
I just reproduced again. Seems that `dev-server setup` with an adapter that fails to compile will trigger this.
@UncleSamSwiss
