### ISSUE TITLE
WebSocket error: Error: connect ECONNREFUSED 127.0.0.1:20426

### ISSUE THREAD

**Issue by xXBJXx** [ioBroker/dev-server#188]
I wanted to try it again today to see if I can reproduce the error, and there it was already at the first startup from dev-server. 

Here is the whole start log [dev-server_log.txt](https://github.com/ioBroker/dev-server/files/8031609/dev-server_log.txt)
I hope you can do something with it.

When the error occurs, it can also sometimes go away after a few seconds, or you make a change in the main.js so that the dev-server establishes a new connection.

I work on Mac, but I have also had this error on Windows.

**Comment by ciddi89** [comment]
I have exactly the same issue on Mac OS.

Here is my log [dev-server-log.txt](https://github.com/ioBroker/dev-server/files/8045097/dev-server-log.txt)

**Comment by UncleSamSwiss** [comment]
The error messages have now been hidden. The only feature that won't work if the WebSocket connection can't be opened ever is to restart the adapter if the config changes.

**Comment by Newan** [comment]
On Windows I have the same error, this error came with the change to ConfigJson Gui:
[dev-server_log.txt](https://github.com/ioBroker/dev-server/files/8691453/dev-server_log.txt)
 
The first run of the dev-server works, but when I stop it (ctrl+c) and restart, the following error comes. If I restart the machine (rebot), the first dev-server command runs fine?

**Comment by ciddi89** [comment]
@Newan When I have the failure for me it helps if I use first the command 'dev server upload' and after that I can use 'dev server watch' and then it works fine. Sometimes but it's really rarely I have to wait few minutes before the connection is fine.
