### ISSUE TITLE
[Improvement / Doku] Anleitung für Einsatz von dev-server mit VS-Code (mittels direktem Link)

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/dev-server#202]
@ english only readers:
I write the following issue in german as it already exists as a german Telegram discussion. If someone needs an english translation, please contact me @mcm1957, I'll do my best. 

- - - 

In Abstimmung mit @UncleSamSwiss lege ich hier (m)eine Anleitung für die Anwendung des dev-servers für das Debuggen reiner Script Adapter unter VS-Code ab und rege an, diesen Ablauf ggF in den dev-server oder eine Aleitung zu übernehmen falls sich bei vertiefter Beurteilung keine Nachteile feststellen lassen.

Vorteil der Link Methode:
JS Script liegt nur genau an einer Stelle und vsCode liest und schreibt genau das eine File

Nachteil:
Adapter muss in VS manuell restartet werden; watch wird nicht verwendet.

Was habe ich gemacht:

A) dev-server installiert und mittels dev-server setup normal initialisisert.

B) Im Verzeichnis .dev-server\default\node_modules den Adapter Tree gelöscht
```
cd .dev-server\default\node_modules
rmdir /s /q ioBroker.<ADAPTERNAME>
```

C) einen Symlink DIREKT von node_modules in mein GIT Verzeichnis eingerichtet
```
mklink /d ioBroker.<ADAPTERNAME> ..\..\..
```

D) den NODE_PATH gesetzt
```
SETX NODE_PATH .dev-server\default\node_modules
```
Kontrolle mittel SET Befehls. Der Output sollte enthalten
Auszug aus Eingabeaufforderung, Befehl SET
```
NODE_PATH=.dev-server/default/node_modules
```

E) setup vsCode Umgebung; dazu folgenden Eintrag in lauch.json Config ergänzen dabei den Namen des Adapterscripts ggf. anpassen falls dieser nicht main.js lautet.
```
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Program",
            "program": "${workspaceFolder}/main.js",
            "args": ["--instance", "0", "--force", "--log"],
            "request": "launch",
            "stopOnEntry": true,
            "console": "internalConsole",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "type": "pwa-node"
        }
  ]
```

F) Zum Debuggen setzte mich nun in das GIT Adapter Verzeichnis und starte dort den dev-server NUR mit run
```
dev-server run
```

Direkt in vsCode starte ich dann den Adaptercode und kann debuggen, den Adapter restarten etc. Scheint bisher alles zu gehen - ausgenommen die run/stop Anzeige im Admin. Aber das ist bei extern gestarten Prozessen ja wohl normal.

**Comment by Garfonso** [comment]
Wo siehst du den Vorteil von mklink gegenüber npm link? 

Ich sehe den Nachteil, dass dann das .git Verzeichnis mit im node_modules erscheint und NPM sich weigern wird weitere module zu installieren / zu aktualisieren (oder?).

**Comment by mcm1957** [comment]
Ich habe zunächst versucht mit npm link zu arbeiten. Allerdings habe ich das nicht wirklich zum Laufen gebracht, da alle npm link Anleitungen von einer "globalen" Installation ausgehen und sich das irgendwie nicht mit dem dev-server vertragen hat. Ich kann allerdings nicht ausschließen, dass ich da mangels ganz konkreter und auf den dev-server passender Anleitung was falsch gemacht habe.

Bezüglich Nachinstallation von Modulen sehe ich wenig Probleme, da es hier ja um den dev-server geht. Einfach den Link löschen und dev-server neu aufsetzen oder module nachinstallieren und link wieder setzen. Die Lösung ist definitiv NICHT für eine produktiv oder auch nur testweise aber vollständig laufende Installation gedacht sondern nur zum Debuggen eines einzelnen Adapters in DVP Umgebung.

Bezüglich Platform - ja da hast du recht. Unter Linux müsste man wohl ln nehmen. 

Das Issue hab ich auch Anregung von UncleSamSwiss erstellt. Wenn es besser geht, ist es mir natürlich nur recht. Ich hab vor allem eine Integration in vcCode evrmisst da das dauernde Umkopieren vom git Verzeichnis ins Verzeichnis in dem der Adapetr läuft für mich lästig war und Änderungen in vsCode dauernd verloren gingen.

**Comment by Garfonso** [comment]
> von einer "globalen" Installation ausgehen

Das Vorgehen dazu ist ganz konkret:

1. `npm link` im git-Ordner ausführen. Das erzeugt den Link vom Repository in das globale node_modules Verzeichnis (also z.B. C:\Users\USERNAME\....\node_modules). 
2. `npm link iobroker.adapter` im devserver Verzeichnis ausführen (also z.B.  .devserver\default). Das Linkt dann das globale wieder zurück. 

Schritt 1 muss nur einmalig ausgeführt werden (außer das git-Verzeichnis wird verschoben).

> zum Debuggen eines einzelnen Adapters

Zum Debuggen von z.B. lovelace, einer Visualisierung, benötige ich regelmäßig andere Adapter um wechselwirkungen zu analysiseren und auch einen gut gefüllte Objektdatenbank um die Darstellung von verschiedenen Objektbäumen anderer Adapter zu analysieren. Insofern wäre da ein regelmäßiges neuaufsetzen relativ aufwendig, aktualisieren und nachinstallieren ist für mich da der einfachere Weg.
Natürlich kann man den link löschen. Der npm link geht umgekehrt auch regelmäßig unter die Räder, hat aber den Vorteil, dass NPM Operationen ohne Fehler durchlaufen und danach der link wiederhergestellt werden kann. 

> Wenn es besser geht, ist es mir natürlich nur recht.

Ich wollte dich nicht angreinfen, sondern das Issue dazu nutzen die Vor- und Nachteile einmal aufzuführen. Da sind deine Erfahrungen mit mklink natürlich hilfreich. :-) Das von Hand umkopieren macht natürlich keinen Sinn, da gebe ich dir Recht.

**Comment by mcm1957** [comment]
Danke für deine Erfahrungen.
Möglicherweise hat es sich bei mir auch beim globalen Verzeichnis deswegen gespießt da ich auf einem (Windows-) Rechner eine normale laufende ioBroker installation habe (- nur zum Testen natürlich-) und parallel dazu den dev-server. Die globale Installation soll(te) nicht die work-in-progress Version verwenden bzw, habe ich dort ganz normal Adapter (auch den in Arbeit befindlichen) vom Repo installiert,

Sobald ich das Ganze das nächste Mal von scratch aufsetze werd ich es nomals via npm link versuchen. An sich macht es ja Sinn die offiziellen Wege zu verwenden.

**Comment by Garfonso** [comment]
Der iobroker installiert adapter auch in seinem node_modules Ordner (also z.B. C:\iobroker\node_modules). Da gibt es also im Normalfall keine Kollision mit den globalen node modulen.

**Comment by mcm1957** [comment]
OBSOLETE

I've created several adapters now using create-adapter including dev-server. Debugging with VS Code worked wiothoiut any special links or other manual tasks.
