### ISSUE TITLE
[setup] Set default language, currency sign (and country / location ?)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/dev-server#237]
These information are empty after ``dev-server setup``

https://github.com/ioBroker/dev-server/blob/2d1846a95bb76f1e32f32e57da2b95fc859399ae/src/index.ts#L1244-L1252

**Comment by Apollon77** [comment]
What we should set? Something static like "Berlin", "DE" and "€" or also configurable (needed because if someone needs to change it he can change it manually)?

**Comment by klein0r** [comment]
Everything is better than an empty configuration. Maybe

```
    "city": "Berlin",
    "country": "Germany",
    "longitude": 13.28,
    "latitude": 52.50,
    "language": "en",
    "tempUnit": "°C",
    "currency": "€",
```

**Comment by Apollon77** [comment]
added to PR
