### ISSUE TITLE
Cannot run dev-server after install

### ISSUE THREAD

**Issue by frankjoke** [ioBroker/dev-server#24]
I wanted to try dev-server today on my windows-machine but could not manage. got always proxy error on the web page.

I then tried on my notebook and it was working there, so I investigated why it did not load on my dev-PC (Windows 10 updated, Node 14.* latest, ...) was same as on notebook.

I found the reason logging at install logs: On the dev-PC I had an ols version from node-gyp and had to install
`npm i -g windows-build-tools` again.
It would be good if you mention in your setup readme part to run this install as well.

p.s.: As my system had I do change port but could not by running a new setup, I had to delete the cache directory and run a clean setup. Maybe it would be great to be able change the port after install as well....

Otherwise it seems to work now. well! Good job done!

One other problem arised on further tests but here it migt be also admin 5.0.6 which was installed by default: I use it to test an adapter with my new react-based config which uses index.html and not index_m.html in admin (also "materialize": false
 in io-package). Admin does not open config but lists just file in admin, if I switch to reacct-mode of admin-5 it works!

**Comment by UncleSamSwiss** [comment]
Sorry, there are way too many issues packed in here (besides general feedback). If you feel, there are still things to be fixed, please create separate issues.

>  had an ols version from node-gyp

dev-server doesn't require anything different than ioBroker. I'm assuming that if you can run ioBroker, you can run dev-server.
If this is not true, I would need log files (in a separate issue as said above).

> As my system had I do change port but could not by running a new setup, I had to delete the cache directory and run a clean setup. Maybe it would be great to be able change the port after install as well....

When trying to run `setup` a second time, message states:
```text
dev-server is already set up in "${this.tempDir}".
Use --force to set it up from scratch (all data will be lost).
```

So, simply calling `dev-server setup --adminPort 8082 --force will do exactly what you want.

There is unfortunately no way to change the port as many different things depend on the admin port number (all internal ports are derived from the admin port to allow multiple parallel installations).

> One other problem arised on further tests but here it migt be also admin 5.0.6 which was installed by default

Always the **latest** version of Admin and js-controller are installed, this is intended. You may change the js-controller version using the `--js-controller` option in `setup`, but there is currently no way to choose the admin-version.

If there is an issue related to ioBroker.admin, please create an issue in the respective repository.
