### ISSUE TITLE
dev-server does not close started adapters gracefully or at all!

### ISSUE THREAD

**Issue by frankjoke** [ioBroker/dev-server#25]
My Adapter also creates an express server to receive data from various sources.

When I want to use dev-server with it I hope my understanding is right to use `dev-server watch` to see updates. 

Nevertheless, after starting once the adapter stays alive even if you stop watch with `^C`. In background I see the node-process with the adapter still running. 
I cannot start adapter again (have to use `netstatat` to find out process number using my port of my adapter server and `taskkill` to kill the task.

Otherwise changes work and adapter get restarted. Problem is only if I need to change something in the config and want to re-run Ihave no command to restart server while in watch mode and need to stop him with `^C`, but then ....

So please make sure that  running adapter is stopped when any of the server modes are stopped by `^C`!

Thanks, otherwise running well so far!

**Comment by UncleSamSwiss** [comment]
Which OS and which NodeJS versions are you using?

**Comment by frankjoke** [comment]
I use Windows 10 latest and nodejs 14.16.1 latest , but anyhow, I believe I can close it because after re-installing the server and the windows nodejs developer packages it seems to work. My only problem is that the proxy you use does not work with al adapter configs and I need to use the 20526 port directly to run admin...

It would be great top get also a link to this admin port listed in the startup routine.
It also would be nice that the server also restarts the watch-adapter instance when the admin restarts the adapter. Currently you have to stop watching and restart it to restart adapter.
