### ISSUE TITLE
fill devserver with predefined set of objects and data

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/dev-server#28]
Devserver is great for testing adapters that "fill" iobroker, i.e. create devices based on hardware devices or pull data from some external source. 

But for testing / developing adapters that show what is already inside iobroker (for example an UI adapter) it can be tedious to (re-)create all the objects and states in ioBroker using the admin interface. For this kind of adapters (especially with automatic device creation moving forward) it would be nice to create a predefined set of objects (and states?) on setup and maybe have a way to `reset` this predefined state (i.e. delete all objects and import the predefined ones - or is delete too much?).

The object definition could be as simple as a JSON file (admin exports objects as { id: ioBrokerObject } JSON).

**Comment by UncleSamSwiss** [comment]
This sounds a lot like a backup-restore situation.
I would suggest, we could define a backup file to be restored when setting up dev-server. Example:
```sh
dev-server setup --backupFile my-great-backup.tgz --adminPort 8082
```

Resetting it to the backup would be a simple `iobroker restore` inside the `.dev-server` directory (except for the fact that you can't simply call `iobroker`, you need to call `node node_modules/iobroker.js-controller/iobroker.js <arguments>` instead).

Also a force setup would of course reload the data:
```sh
dev-server setup --backupFile my-great-backup.tgz --adminPort 8082 --force
```

What do you think?

**Comment by UncleSamSwiss** [comment]
In addition to restoring a backup file, I will also introduce the concept of "profiles" allowing to easily choose between different environments: https://github.com/ioBroker/dev-server/issues/39

**Comment by Garfonso** [comment]
Sounds good to me.
