### ISSUE TITLE
changing of io-package.json does not trigger upload (dev-server watch mode)

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/dev-server#299]
The dev-server running in watch mode seems to be missing changes to io-package.json.

I've added common.messagebox to the dev-server wondering why this did not work. I had to perform a manual dev-server upload to make it working.

Please check whether watching io-package.json and triggering an automatic upoad could be implemented without much effort and without considerable runtime load (as changing io-package will be ruther seldom)

**Comment by UncleSamSwiss** [comment]
I don't think it makes sense to do an upload for every change to io-package.json. The few times the user changes this file, it should be ok for him to do a `dev-server upload` as written in the documentation:
https://github.com/ioBroker/dev-server#dev-server-upload

**Comment by mcm1957** [comment]
Ok to cöpse from my side.

Sorry, i did not read the docu.

Running away .....
