### ISSUE TITLE
"dev-server-watch" is not starting properly

### ISSUE THREAD

**Issue by Seqway** [ioBroker/dev-server#300]
I am developing a new adapter and using the dev server.
This one is installed on Proxmox as a CT and has full 4 CPUs and 1GB Ram.
Ram is round about 400-500 when dev-server is started and CPU is at 15-20% maximum.

Please see attached the log file from iobroker and from dev-server.
Here you have some more output from dev-server --> [devserverlog](https://pastebin.com/pGeBeszA)

In the developer starter group the first idea was that maybe the connection is not too slow but maybe to fast because iobroker does not seem to see that the adapter instance was already starting ? Just a guess.

[opnsense_log.txt](https://github.com/ioBroker/dev-server/files/9678626/opnsense_log.txt)
[devserverlog.txt](https://github.com/ioBroker/dev-server/files/9678629/devserverlog.txt)

**Comment by UncleSamSwiss** [comment]
Honestly, dev-server is **not** meant to be used on a machine different than the developer PC. It runs under Windows, MacOS and Linux mostly without issues, but using LXC containers is not officially supported.

If you want to test your adapter on a LXC container, simply install ioBroker and then install the adapter inside ioBroker.

If you want to develop the adapter on your PC, follow the preliminary "Getting Started" under https://iobroker.github.io/dev-docs/getting-started/01-installation/

**Comment by Seqway** [comment]
Nice answer !
By the way, colleague has same issue like me and runs dev-server locally on his Mac machine. It is a pity not to ask for further explanation and just simply close the thread. I just told my setup nothing more ... also I do not read in the documentation that it is NOT allowed to install dev-server on a VM.
and also there are official YT videos who exactly do the same like me.

But ok, I understand and take my consequences.
Thanks !

**Comment by Apollon77** [comment]
@UncleSamSwiss I think this has nothing to do if it is proxmox or not ... I will try something
