### ISSUE TITLE
Include .DS_Store file in the standard .gitignore

### ISSUE THREAD

**Issue by Seqway** [ioBroker/dev-server#315]
Hello,
as a Mac user i am facing the problem that MacOS (Finder) creates everywhere the .DS_Store file which causes some strange behaviour e.g. in VS Code because the files are always been shown as modified.
So i need to manually do it in the .gitignore

maybe it is a good idea to implement it in the standard so that especially for Mac Users it is not forgotten to exclude this file !

**Comment by Apollon77** [comment]
wrong rtepo? I zjimnk you meaned adapter-creator or?
