### ISSUE TITLE
Support for developing/debugging js-controller itself

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/dev-server#42]

**Comment by UncleSamSwiss** [comment]
Basically this can be done by adding a few `if (this.adapterName === 'js-controller') {` and doing things differently for js-controller.

It would probably be best to have a method `isJsController()` so code stays simple and we don't have the risk of typos in the string comparison.

What comes to my mind:
- setup:
   - don't install js-controller with `npm install` (but install it before uploading admin!)
   - make sure the setup script is called
- watch / debug
   - don't start js-controller and then the adapter, but rather simply js-controller in debug or watch mode
