### ISSUE TITLE
dev-server startet nicht mehr. 

### ISSUE THREAD

**Issue by aruttkamp** [ioBroker/dev-server#428]
Ich habe ein Problem mit dem dev-server. ich bekomme ihn nicht gestartet.

Im Terminalfenster wird mir dieser Fehler angezeigt nach ausführen von dev-server run 

```
Error: Couldn't start js-controller
    at DevServer.waitForJsController (C:\Users\aruttkamp\AppData\Roaming\npm\node_modules\@iobroker\dev-server\dist\index.js:444:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.startJsController (C:\Users\aruttkamp\AppData\Roaming\npm\node_modules\@iobroker\dev-server\dist\index.js:454:9)
    at async DevServer.run (C:\Users\aruttkamp\AppData\Roaming\npm\node_modules\@iobroker\dev-server\dist\index.js:296:9)
    at async Object.handler (C:\Users\aruttkamp\AppData\Roaming\npm\node_modules\@iobroker\dev-server\dist\index.js:100:162)
```

Inhalt der Log-datei : 
```
[iobroker.2023-08-15.log](https://github.com/ioBroker/dev-server/files/12352248/iobroker.2023-08-15.log)
```

admin 6.8.0 node: v18.17.1, js-controller: 5.0.11  Windows 11

dev-server setup --force , sowie löschen von .dev-server und erneutes setup habe ich ausgeführt. 

Lief alles bis ich den jsController updaten wollte und dev-server update ausgeführt habe.

**Comment by AlCalzone** [comment]
Scheint zu knallen wenn die objects/states ports vom Admin nach 30s nicht belegt sind:
https://github.com/ioBroker/dev-server/blob/54e8e8609188b1f355af3e9a29707d4aa3f06804/src/index.ts#L569-L575

**Comment by aruttkamp** [comment]
Ich habe das Problem durch löschen des Arbeitsverzeichnisses und neuaufsetzen gelöst.

**Comment by AlCalzone** [comment]
Dann gerne Issue schließen, falls gelöst

**Comment by aruttkamp** [comment]
Leider nicht. es passiert immer wieder und ich muss immer wieder neu "anfangen"

**Comment by AlCalzone** [comment]
Konntest du herausfinden, mit welchen Schritten es kaputt geht? Würde helfen zu reproduzieren.

**Comment by aruttkamp** [comment]
> Konntest du herausfinden, mit welchen Schritten es kaputt geht? Würde helfen zu reproduzieren.
Genau das muss ich machen. Zeit ist grad das problem - aber es kommt denke ich nächste Woche ( da hab ich urlaub )

**Comment by aruttkamp** [comment]
ok. ich habe jetzt mal Schritt für Schritt alles mitgeschrieben ;-) 
Nach Installation des Release Scripts geht es nicht mehr !
Vielleicht mache ja auch ich was falsch - frage z.B. warum muss ich das  release script neu installieren ? 
aber der Reihe nach : 

Clonen des github Archivs mit VSC ( https://github.com/aruttkamp/ioBroker.rct )
Install dev-server (npm install --global @iobroker/dev-server)
dev-server setup
dev-server run ----- läuft wir erwartet. dev-server startet und debugging ist möglich.
Sicherung des Kompletten Ordners d:\ioBroker angelegt.
bischen was gecoded
dev-server gestoppt.
dev-server gestartet - kein Problem
Änderungen mit Github synchronisiert
npm run release patch  --> Fehler , weil release Script nicht vorhanden. 
npm i -D @alcalzone/release-script
dev-server run -----> Fehler tritt auf wie oben dokumentiert.
npm run release patch ( läuft jetzt fehlerfrei ) 

Freue mich auf Hilfe.

**Comment by Apollon77** [comment]
@aruttkamp Asasked in telegram please post FULL shell logs from starting try of dev-server and additionally the iobroker.log from this test instace (.dev-server/logs/iobroker. ...)

**Comment by AlCalzone** [comment]
Meine Frage von oben ist leider noch nicht vollständig beantwortet:

Befindet sich ggf. in `D:\ioBroker` eine package.json, package-lock.json oder node_modules?
Und wie sieht's aus in `D:\`?

**Comment by aruttkamp** [comment]
> Befindet sich ggf. in `D:\ioBroker` eine package.json, package-lock.json oder node_modules?
> Und wie sieht's aus in `D:\`?

in D:\ioBroker und in D:\ befindet sich keine der genannten Dateien !

**Comment by AlCalzone** [comment]
Ok, geht's beim Installieren von Abhängigkeiten via `npm` kaputt. Meine Vermutung - das muss weg:

https://github.com/aruttkamp/ioBroker.rct/blob/a491228c9c14401bd9b5c20082d00ab7d215a303/package.json#L25

dev-server wird global installiert, nicht lokal. Und wenn du schon dabei bist, nimm die Zeile auch noch raus:
https://github.com/aruttkamp/ioBroker.rct/blob/a491228c9c14401bd9b5c20082d00ab7d215a303/package.json#L53

Danach `npm install` um das Lockfile wieder gerade zu ziehen.

**Comment by aruttkamp** [comment]
Moin ! 
Beides wurde eingebaut um das Problem zu lösen. 
Vorher waren beide Zeilen nicht vorhanden und der dev-server global installiert. 
Ich stelle gleich noch die Log´s zur Verfügung.

**Comment by AlCalzone** [comment]
Ok gerade verifiziert:
package.json wie folgt ändern:
![grafik](https://github.com/ioBroker/dev-server/assets/17641229/f6bd5f35-d7d4-49f2-a171-9a994edbc471)

Folgendes löschen:
```
node_modules/
iobroker-data/
iob
iobroker
```

Dann glattziehen:
```
npm install
dev-server setup --force
```

**Comment by aruttkamp** [comment]
> iob
> iobroker

Was ist hiermit gemeint ? 
Die Ordner gibts doch gar nicht .. bzw. die Dateien. 

Rest ist mir klar.

**Comment by Apollon77** [comment]
Du hast den js-controller elbst als Dependency gesetzt und das hat dinge installiert die nicht erwartet waren. Das ist das Problem. Das und die Auswirkungen davon musst Du jetzt manuell beheben

**Comment by aruttkamp** [comment]
ok ok ok .... 
VIELEN DANK ! 
Wie immer das da reingekommen ist .. muss mit meinem ersten commit nach der Übernahme des Projekts passiert sein. Ich habe die Anpassungen vorgenommen und so wie es jetzt aussieht geht es !! :-D

Vielen Dank an @Apollon77 und @AlCalzone 
Ich räume jetzt noch ein wenig auf und teste es die nächsten Tage.

**Comment by AlCalzone** [comment]
> Die Ordner gibts doch gar nicht .. bzw. die Dateien.

Bei mir gabs die als ich deine Repro nachvollzogen habe.
