### ISSUE TITLE
Dev-Server läuft mit setup ; upload oder watch nicht durch

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/dev-server#455]
Ich habe das Problem, dass der Dev-Server nicht im setup durchläuft.
Ich  habe zuerster mit:

`npm install --global @iobroker/dev-server`

den neusten dev-server installiert.

dann folgte:

`PS C:\ioBrokerAdapter\ioBroker.smoothed> dev-server setup
Using default profile default
Using profile name "default"
Using adapter name "smoothed"
Setting up in C:\ioBrokerAdapter\ioBroker.smoothed\.dev-server\default
Verifying .npmignore and .gitignore
C:\ioBrokerAdapter\ioBroker.smoothed> npm pack --dry-run
C:\ioBrokerAdapter\ioBroker.smoothed> git status --short --untracked-files=all
Installing js-controller and admin...
C:\ioBrokerAdapter\ioBroker.smoothed\.dev-server\default> npm install --loglevel error --production
[##################] / reify:lodash: timing reifyNode:node_modules/moment Completed in 16149ms`

es bleibt IMMER bei node_modules/moment hängen und läft nicht mehr weiter.

Kann ich was machen, oder gibt es da einen Fehler?

Ohne dev-server ist etwas blöd zu entwickeln, wenn man nicht testen kann.

**Comment by Apollon77** [comment]
@BenAhrdt noch relevant? Dachte ist gefixt?

**Comment by BenAhrdt** [comment]
@Apollon77 ja sorry. Sollte gefixt sein.
