### ISSUE TITLE
Automatically add `.dev-server` to `.npmignore` (if it exists)

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/dev-server#46]

**Comment by UncleSamSwiss** [comment]
And probably also to .gitignore.

I wouldn't automatically modify files the user checks in, but at least ask him if we should do it for him.

Thing is: if the latest adapter creator is used, the npmignore already contains the wildcard for dot-directories, but many developers have old .npmignore files.

**Comment by AlCalzone** [comment]
Yup, I noticed when I debugged an existing adapter with dev-server.
