### ISSUE TITLE
skip new admin 5 intro tab

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/dev-server#60]
Not sure if possible... but if somehow possible, we should try to skip that for devserver (might be as easy as set some object?).

**Comment by Garfonso** [comment]
somehow the intro tab is not displayed anymore... did you change something or did admin change (again)?

**Comment by UncleSamSwiss** [comment]
Didn't touch anything. My assumption would be: it is stored in a cookie, thus reinstalling dev-server will not change that value.
